shared-ui:
  - changed-files:
    - any-glob-to-any-file:
      - 'packages/ui/**'

charts:
  - changed-files:
    - any-glob-to-any-file:
      - 'packages/charts/**'

tokens:
  - changed-files:
    - any-glob-to-any-file:
      - 'packages/tokens/**'

storybook:
  - changed-files:
    - any-glob-to-any-file:
      - 'apps/storybook/**'

utils:
  - changed-files:
    - any-glob-to-any-file:
      - 'packages/*/src/utils/**'

style:
  - changed-files:
    - any-glob-to-any-file:
      - '**/*.css'
      - '**/*.scss'
      - '**/*.sass'
      - 'packages/*/src/styles/**'
      - 'packages/tokens/**'

tests:
  - changed-files:
    - any-glob-to-any-file:
      - '**/__tests__/**'
      - '**/*.test.{ts,tsx}'

config:
  - changed-files:
    - any-glob-to-any-file:
      - '**/.eslintrc*'
      - '**/eslint.config.*'
      - '**/.prettierrc*'
      - '**/*.config.{js,ts,cjs,mjs}'
      - '**/tsconfig*.json'
      - '.lintstagedrc.*'
      - 'packages/configs/**'
      - 'turbo.json'
      - 'pnpm-workspace.yaml'

build:
  - changed-files:
    - any-glob-to-any-file:
      - 'packages/*/scripts/**'

docs:
  - changed-files:
    - any-glob-to-any-file:
      - 'docs/**'
      - '**/*.md'
      - '**/*.mdx'

ci:
  - changed-files:
    - any-glob-to-any-file:
      - '.github/workflows/**'
      - '.github/actions/**'

deps:
  - changed-files:
    - any-glob-to-any-file:
      - '**/package.json'
      - 'pnpm-lock.yaml'
